In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

D:\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [3]:
data = pd.read_csv('diabetes.csv')
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [4]:
feature_not_zero = ['Glucose' , 'BloodPressure' , 'SkinThickness' , 'Insulin' , 'BMI' , 'DiabetesPedigreeFunction' , 'Age']

for c in feature_not_zero :
    data[c] = data[c].replace(0 , np.nan)
    mean = int(data[c].mean(skipna = True))
    data[c] = data[c].replace(np.nan , mean)

In [5]:
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,155.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,155.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,155.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,29.0,155.0,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,72.0,29.0,155.0,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,29.0,155.0,32.0,0.232,54,1

In [6]:
norma = StandardScaler()

x = data.iloc[: , :-1]
y = data.iloc[: , -1]

x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.25 , random_state = 42)

x_train = norma.fit_transform(x_train)
x_test = norma.transform(x_test)

In [7]:
x_train

array([[ 2.80346794,  0.24255766, -0.02111222, ...,  1.10365617,
         0.29608546,  0.96352088],
       [ 0.07832678,  0.24255766,  1.13704389, ...,  0.40522211,
        -0.70087555, -0.86295593],
       [-0.22446668, -2.02000446,  0.80614215, ...,  0.30336714,
        -0.66548048,  1.13747105],
       ...,
       [ 1.89508755, -0.68908557,  1.13704389, ...,  1.93304662,
         1.96850229,  0.44167036],
       [-1.13284707,  0.64183333, -0.02111222, ...,  1.46742391,
        -0.77756486, -0.34110542],
       [-1.13284707,  0.10946577,  1.96429826, ..., -1.42816731,
        -0.6094383 , -1.03690611]])

In [8]:
x_test

array([[ 0.6839137 , -0.78890448, -1.17926833, ...,  0.2451643 ,
        -0.11390738,  0.87654579],
       [-0.52726014, -0.32308287,  0.22706409, ...,  0.49252636,
        -0.94569142, -1.03690611],
       [-0.52726014, -0.45617476, -0.68291571, ..., -0.22045841,
        -0.91619553, -1.03690611],
       ...,
       [ 0.6839137 ,  0.04291982, -0.02111222, ...,  0.18696146,
         0.77981801,  0.09377001],
       [-0.22446668, -1.45436393, -1.84107183, ..., -0.19135699,
        -0.65073254, -0.60203068],
       [-0.22446668, -0.52272071, -0.02111222, ..., -0.94799389,
        -0.77166568, -0.51505559]])